<?php
// File: components/print_helper.php

/**
 * Generates a print-friendly version of the provided content
 * 
 * @param string $content The HTML content to print
 * @param string $title Optional title for the printed page
 * @return void Opens a new window with print-friendly content
 */
function generatePrintableContent($content, $title = 'The Salty Parrot - Generated Content') {
    ?>
    <script>
        // Create print window
        const printWindow = window.open('', '_blank');
        
        // Create print-friendly HTML
        printWindow.document.write(`
            <!DOCTYPE html>
            <html>
            <head>
                <title><?php echo $title; ?></title>
                <style>
                    body {
                        font-family: Arial, sans-serif;
                        line-height: 1.6;
                        color: #333;
                        padding: 20px;
                    }
                    
                    h2, h3 {
                        color: #805d2c;
                    }
                    
                    .loot-card, .ship-details {
                        border: 1px solid #ddd;
                        padding: 15px;
                        margin: 15px 0;
                        border-radius: 8px;
                    }
                    
                    .loot-roll, .loot-name {
                        color: #805d2c;
                    }
                    
                    .loot-category {
                        font-style: italic;
                        color: #666;
                    }
                    
                    .ancient-relic-badge {
                        display: inline-block;
                        padding: 3px 8px;
                        background-color: #f0e6ff;
                        color: #4b0082;
                        border: 1px solid #9d4edd;
                        border-radius: 12px;
                        font-size: 0.8rem;
                        margin-right: 5px;
                    }
                    
                    .thing-of-importance-badge {
                        display: inline-block;
                        padding: 3px 8px;
                        background-color: #e6ffe6;
                        color: #006400;
                        border: 1px solid #2ea44f;
                        border-radius: 12px;
                        font-size: 0.8rem;
                        margin-right: 5px;
                    }
                    
                    ul {
                        list-style-type: none;
                        padding-left: 0;
                    }
                    
                    li {
                        margin-bottom: 10px;
                        position: relative;
                        padding-left: 20px;
                    }
                    
                    li:before {
                        content: '•';
                        color: #805d2c;
                        position: absolute;
                        left: 0;
                        top: 0;
                    }
                    
                    .extra-roll-divider {
                        text-align: center;
                        margin: 20px 0;
                        position: relative;
                    }
                    
                    .extra-roll-divider::before {
                        content: "";
                        position: absolute;
                        top: 50%;
                        left: 0;
                        right: 0;
                        height: 1px;
                        background-color: #ddd;
                        z-index: 0;
                    }
                    
                    .extra-roll-divider span {
                        position: relative;
                        background-color: white;
                        padding: 0 15px;
                        z-index: 1;
                    }
                    
                    .output-placeholder {
                        display: none;
                    }
                </style>
            </head>
            <body>
                <h2><?php echo $title; ?></h2>
                <?php echo $content; ?>
                <div style="margin-top: 30px; font-size: 0.8rem; text-align: center; color: #666;">
                    <p>Generated by The Salty Parrot - A Pirate Borg Toolbox</p>
                    <p>The Salty Parrot is an independent production by Stuart Greenwell. It is not affiliated with Limithron LLC.<br>
                    It is published under the PIRATE BORG Third Party License. PIRATE BORG is ©2022 Limithron LLC.</p>
                </div>
            </body>
            </html>
        `);
        
        // Close document for printing
        printWindow.document.close();
        
        // Wait for content to load and then print
        printWindow.addEventListener('load', function() {
            printWindow.print();
        });
    </script>
    <?php
}
?>
